---

scenario:
  name: statsd

driver:
  name: docker

dependency:
  name: galaxy

lint:
  name: yamllint

platforms:
  # - name: ubuntu1404
  #   image: geerlingguy/docker-ubuntu1404-ansible:latest
  #   privileged: true
  #   volume_mounts:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /sbin/init
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  directory: ../resources/tests/all
  lint:
    name: flake8
