---

- name: Converge
  hosts: all
  connection: local

  vars_files:
    - ../resources/vars/statsd-common.yaml
    - ../resources/vars/nodejs-common.yaml

  pre_tasks:
    - name: include tasks for preconf
      import_tasks: ../resources/preconf.yml

  roles:
    - role: geerlingguy.nodejs
    - role: ansible-role-statsd
