---

- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: install packages for testinfra socket test
  package:
    name: net-tools
    state: present
